### ISSUE TITLE
What would you use to make the switches swappable?

### ISSUE THREAD

**Issue by RichardBronosky** [LifeIsOnTheWire/Postage-Board#1]
I'm planning to do a hand wire, but was going to use [Kailh sockets](https://novelkeys.xyz/products/kailh-pcb-sockets). Does this board preclude that? If so, which of the tubes might you suggest for MX clone switches?

**Comment by LifeIsOnTheWire** [comment]
The board doesn't support sockets.  Im not sure why you would want to do that anyways, only the 3x switches on the postage board would be swappable.  Are you going to desolder and dismantle the rest of your matrix wiring every time you swap switches?

**Comment by kdb424** [comment]
I think what they mean is they were going to place the kailh hot swap sockets on the switches, and solder those into basically a harness. I intend to do the same with my custom that I'm working on now. I could then change switches at will by lifting the harness off of the switches, changing switches in the plate, and resting the harness back on them, much like the PCB's are just a hot swap socket holder. Best of both worlds that way, and yes, they are secure enough believe it or not.

**Comment by LifeIsOnTheWire** [comment]
Gotcha.  It wasn't possible to fit them on the PCB anyways.  There are far too many traces running between the switch pin holes to allow for larger holes.
